#!/usr/bin/env bash

THIS_DIR=$(cd $(dirname $0); pwd)
cd $THIS_DIR

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++ libjansson-dev libpython-dev expat libexpat1-dev -y
cd..

Now Send cd AntiSpamCreatorBot then ./launch.sh install then ./launch.sh


 #Channel: @TGland
 #IT Channel: @ITTGland
